config/routes.rb
TruckFoodApp::Application.routes.draw do
  get "new_users/new"
  resources :trucks

match '/home' => 'pages_controller#home', :via => [:get]
match '/about' => 'pages_controller#about',  :via => [:get]
match '/contact'=> 'pages_controller#contact',:via => [:get]

end

app/models/truck.rb
class Truck < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller_controller.rb
class PagesControllerController < ApplicationController
end

app/controllers/trucks_controller.rb
class TrucksController < ApplicationController
  before_action :set_truck, only: [:show, :edit, :update, :destroy]

  # GET /trucks
  # GET /trucks.json
  def index
    @trucks = Truck.all
  end

  # GET /trucks/1
  # GET /trucks/1.json
  def show
  end

  # GET /trucks/new
  def new
    @truck = Truck.new
  end

  # GET /trucks/1/edit
  def edit
  end

  # POST /trucks
  # POST /trucks.json
  def create
    @truck = Truck.new(truck_params)

    respond_to do |format|
      if @truck.save
        format.html { redirect_to @truck, notice: 'Truck was successfully created.' }
        format.json { render action: 'show', status: :created, location: @truck }
      else
        format.html { render action: 'new' }
        format.json { render json: @truck.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trucks/1
  # PATCH/PUT /trucks/1.json
  def update
    respond_to do |format|
      if @truck.update(truck_params)
        format.html { redirect_to @truck, notice: 'Truck was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @truck.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trucks/1
  # DELETE /trucks/1.json
  def destroy
    @truck.destroy
    respond_to do |format|
      format.html { redirect_to trucks_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_truck
      @truck = Truck.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def truck_params
      params.require(:truck).permit(:title, :food_truck_name, :food_truck_url, :type_of_food)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_controller_helper.rb
module PagesControllerHelper
end

app/helpers/trucks_helper.rb
module TrucksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TruckFoodApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages_controller/about.html.erb
<html>
  <head>
    <title></title>
  </head>
  	<h1>About Us</h1>
  		<div>
  			<a href="home">Home</a>
  			<a href="about">About</a>
  			<a href="trucks">Truck Database</a>
  		</div>
  	<body>
  	</body>
</html>

app/views/pages_controller/contact.html.erb
<html>
  <head>
    <title></title>
  </head>
  	<h1>Contact Us</h1>
  		<div>
  			<a href="home">Home</a>
  			<a href="contact">Contact Us</a>
  			<a href="trucks">Truck Database</a>
  		</div>
  	<body>
  	</body>
</html>

app/views/pages_controller/home.html.erb
<!DOCTYPE>

<html>
  <head>
    <title></title>
  </head>
  	<header>
      <h1>Truck-a-ba-loo</h1>
      <nav id= "menu">
        <ul>
          <li><a href="about">About</a></li>
          <li><a href="contact">Contact Us</a></li>
          <li><a href="trucks">Truck Database</a></li>
          <li>Sign in</li>
        </ul>
      </nav>
    </header>
    <section id = "cover" style ="background-image: url('http://farm7.staticflickr.com/6188/6117251799_653d539d41_o.jpg')"></section>  
    <div class = "content">
    <div class = "divider"><img style= 'width:50%;' src= "http://im1.shutterfly.com/media/47a4da31b3127ccef581d81c9fd500000030O00QatmjNs2cNwe3nwA/cC/f%3D0/ls%3D00708660346520140411015108455.JPG/ps%3D50/r%3D0/rx%3D720/ry%3D480/"/></div>
      <section id = "Trucks" data-scroll-index = "01">
          <div class = "wrapper">
            <div class = "intro">
              <h2>Our Trucks</h2>
              <h3>The best selection of food trucks New York has to offer</h3>
              <ul class ="grid">
                <li>
                  <a href ="trucks"><img src = "http://www.bobjo.net/images/sm_menu/bbb_sm.jpg"/>
                  <div class = "caption"><span>Bob & Jo</span></div>
                  </a>
                </li>
                 <li>
                  <a href ="trucks"><img src = "http://www.korillabbq.com/sites/default/files/emptybox_logo.png"
                  /></a>
                  </li>
                </li>
                  </a>
                </li>
                <li></li>
                
              
      </section>
      <section id = "About" data-scroll-index = "02"></section>
      <section id = "contact" data-scroll-index = "03"></section>
    </div>
    <body>
    </body>
</html>


        

app/views/trucks/_form.html.erb
<%= form_for(@truck) do |f| %>
  <% if @truck.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@truck.errors.count, "error") %> prohibited this truck from being saved:</h2>

      <ul>
      <% @truck.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p>   
    <a href="home">Home</a>
    <a href="contact">Contact Us</a>
    <a href="trucks">Truck Database</a>
 </p>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :food_truck_name %><br>
    <%= f.text_field :food_truck_name %>
  </div>
  <div class="field">
    <%= f.label :food_truck_url %><br>
    <%= f.text_area :food_truck_url %>
  </div>
  <div class="field">
    <%= f.label :type_of_food %><br>
    <%= f.text_field :type_of_food %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/trucks/edit.html.erb
<h1>Editing truck</h1>

<%= render 'form' %>

<%= link_to 'Show', @truck %> |
<%= link_to 'Back', trucks_path %>

app/views/trucks/index.html.erb
<h1>Food Trucks in NYC</h1>
<div>   
  <a href="home">Home</a>
  <a href="contact">Contact Us</a>
  <a href="trucks">Truck Database</a>
 </div>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Food truck name</th>
      <th>Food truck url</th>
      <th>Type of food</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @trucks.each do |truck| %>
      <tr>
        <td><%= truck.title %></td>
        <td><%= truck.food_truck_name %></td>
        <td><%= truck.food_truck_url %></td>
        <td><%= truck.type_of_food %></td>
        <td><%= link_to 'Show', truck %></td>
        <td><%= link_to 'Edit', edit_truck_path(truck) %></td>
        <td><%= link_to 'Destroy', truck, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Truck', new_truck_path %>

app/views/trucks/new.html.erb
<h1>New truck</h1>

<%= render 'form' %>

<%= link_to 'Back', trucks_path %>

app/views/trucks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @truck.title %>
</p>

<p>
  <strong>Food truck name:</strong>
  <%= @truck.food_truck_name %>
</p>

<p>
  <strong>Food truck url:</strong>
  <%= @truck.food_truck_url %>
</p>

<p>
  <strong>Type of food:</strong>
  <%= @truck.type_of_food %>
</p>

<%= link_to 'Edit', edit_truck_path(@truck) %> |
<%= link_to 'Back', trucks_path %>
<p>>  			<a href="home">Home</a>
  			<a href="contact">Contact Us</a>
  			<a href="trucks">Truck Database</a>
 </p>